service: aws-web3-layer
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  region: us-east-1

layers:
  web3:
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - nodejs8.10
